INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '654 S Myers St', 'Los Angeles', 'California', '94027', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '655 S Myers St', 'Los Angeles', 'California', '94027', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', 'W Jefferson Dr', 'Los Angeles', 'California', '94027', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '10000 Washington Blvd', 'Los Angeles', 'California', '94027', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '189 The Grove Dr', 'Los Angeles', 'California', '94027', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '4305 La Jolla Village Dr', 'San Diego', 'California', '94027', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '15505 Long Vista Dr # 210', 'Austin', 'Texas', '20001', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '8002 Burleson Rd', 'Austin', 'Texas', '20001', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '3121 Palm Way', 'Austin', 'Texas', '20001', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '5085 Westheimer Rd', 'Houston', 'Texas', '20001', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '6 W 35th St', 'New York', 'New York', '10001', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '14 Hall St, Brooklyn', 'New York', 'New York', '10001', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '767 5th Ave', 'New York', 'New York', '10001', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', 'Terminal, 45 Grand Central', 'New York', 'New York', '10001', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '940 Madison Ave', 'New York', 'New York', '10001', 'USA');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '9, Jalan Tandang 204a', 'Kuala Lumpur', 'Selangor', '40150', 'Malaysia');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '3RD FLOOR, Petronas Twin Tower', 'Kuala Lumpur', 'Selangor', '40150', 'Malaysia');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', 'G-063, Mid Valley Megamall', 'Kuala Lumpur', 'Selangor', '40150', 'Malaysia');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', 'Level 11 Menara CIMB, Jalan Stesen Sentral 2', 'Kuala Lumpur', 'Selangor', '40150', 'Malaysia');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', 'First Floor, AEON Mall', 'Cheras', 'Selangor', '40150', 'Malaysia');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '2 Chome-33-8 Kitazawa', 'Shibuya', 'Tokyo', '99687', 'Japan');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '1 Chome-20-9 Jinnan', 'Shibuya', 'Tokyo', '99687', 'Japan');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '4 Chome-2-13 Jingumae', 'Shibuya', 'Tokyo', '99687', 'Japan');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '〒101-0021 Tokyo', 'Akihabara', 'Tokyo', '99687', 'Japan');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '3 Chome-5-12 Ginza', 'Harajuku', 'Tokyo', '99687', 'Japan');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', 'Ty-Glas Ave, Llanishen', 'Cardiff', 'Wales', '48643', 'England');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '10 Duke St', 'Cardiff', 'Wales', '48643', 'England');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '63-66 Grand Arcade, St Davids Centre', 'Cardiff', 'Wales', '48643', 'England');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '133 Fountainbridge', 'Edinburgh', 'Scotland', '48643', 'England');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '10 Princes St', 'Edinburgh', 'Scotland', '48643', 'England');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', 'Shan Mei St', 'Tai Long Wan', 'Sha Tin', '90033', 'Hong Kong');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '8-10 Siu Lek Yuen Road', 'Tai Long Wan', 'Sha Tin', '90033', 'Hong Kong');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '沙田正街18號 新城市廣場1期L4/426-428', 'Tai Long Wan', 'Sha Tin', '90033', 'Hong Kong');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '銅鑼灣勿地臣街1號時代廣場第1座24字樓2401室', 'Tai Long Wan', 'Sha Tin', '90033', 'Hong Kong');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '25號 Canton Rd', 'Tai Long Wan', 'Sha Tin', '90033', 'Hong Kong');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '3/175 Jackson Rd, Sunnybank Hills', 'Brisbane', 'Queensland', '23901', 'Australia');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '8 McLachlan St, Fortitude Valley', 'Brisbane', 'Queensland', '23901', 'Australia');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '1151 Creek Road', 'Brisbane', 'Queensland', '23901', 'Australia');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', 'MacArthur Chambers, 233 Queen Street', 'Brisbane', 'Queensland', '23901', 'Australia');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', 'Australia Fair Shopping Centre, 42 Marine Parade', 'Gold Coast', 'Queensland', '23901', 'Australia');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '968 U Chu Liang Bldg.', 'Krabi', 'Krabi', '11111', 'Thailand');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '254/5, Krabi Noi, Mueang Krabi District', 'Krabi', 'Krabi', '11111', 'Thailand');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', 'Haidian District', 'Beijing', 'Beijing', '79218', 'China');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', 'Minhang District', 'Shanghai', 'Shanghai', '79218', 'China');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '71 Di''anmen W St, Shi Cha Hai, Xicheng District', 'Beijing', 'Beijing', '79218', 'China');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '131 Xidan N St, Xi Dan, Xicheng District', 'Beijing', 'Beijing', '79218', 'China');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '101 Chaoyang N Rd', 'Beijing', 'Beijing', '79218', 'China');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', 'Dongcheng, Wangfujing', 'Shanghai', 'Shanghai', '79218', 'China');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Warehouse', '22753 Dewdney Trunk Rd', 'Maple Ridge', 'Vancouver', '99431', 'Canada');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Office', '3030 Lincoln Ave #211', 'Coquitlam', 'Vancouver', '99431', 'Canada');
INSERT INTO premise(premise_type, premise_address, loc_city, loc_state, loc_postcode, loc_country) VALUES ('Store', '2929 Barnet Hwy', 'Coquitlam', 'Vancouver', '99431', 'Canada');